name: Docker build and push

on:
  release:
    types: [published, edited]

jobs:
  pipeline:
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    env:
      RELEASE_REF: ${{ github.ref }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v2
      - name: Build Go App
        run: |
          go build
      - name: Test Go App
        run: |
          go test
      - name: Build Docker image
        run: |
          RELEASE_VERSION=$(echo "$RELEASE_REF" | sed "s|refs\/tags\/v||g")
          docker build . --file Dockerfile --tag unfor19/drone-terraform:${RELEASE_VERSION}
      - name: Push Docker image to registry
        run: |
          echo '${{ secrets.DOCKER_PASSWORD }}' | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push unfor19/drone-terraform:${RELEASE_VERSION}
