name: Docker build and push

on:
  release:
    types: [published, edited]

jobs:
  pipeline:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    env:
      RELEASE_REF: ${{ github.ref }}
      CGO_ENABLED: 0

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v2
      - name: Build Go App
        run: |
          go build -ldflags "-s -w -X main.revision=$(git rev-parse HEAD)" -a
      - name: Test Go App
        run: |
          go test
      - name: Build Docker image
        run: |
          docker build . --file Dockerfile --tag unfor19/drone-terraform:${RELEASE_REF} --tag unfor19/drone-terraform:${RELEASE_REF}-$(git rev-parse --short HEAD)
      - name: Push Docker image to registry
        run: |
          echo '${{ secrets.DOCKER_PASSWORD }}' | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push unfor19/drone-terraform:${RELEASE_REF}
          docker push unfor19/drone-terraform:${RELEASE_REF}-$(git rev-parse --short HEAD)
