name: Docker build and push

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and push
      run: | 
         docker build . --file Dockerfile --tag unfor19/drone-terraform:dev
         echo '${{ secrets.DOCKER_PASSWORD }}' | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
         docker push unfor19/drone-terraform:dev
         
      
