name: Testing

on: push

jobs:
  testing:
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    env:
      CGO_ENABLED: 0

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v2
      - name: Build Go App
        run: |
          go build -ldflags "-s -w -X main.revision=$(git rev-parse HEAD)" -a
      - name: Test Go App
        run: |
          go test -cover -coverprofile=coverage.out
